function getFortune() {
const fortunes = [
  "You will experience great success in the near future.",
  "Good things will come to you in due time.",
  "Your future looks bright and promising.",
  "You will find love and happiness in unexpected places.",
  "Your determination will lead to success and fulfillment.",
  "A new adventure awaits you in the near future.",
  "You will achieve your goals and dreams through hard work and dedication.",
  "Your unique talents and skills will lead to success and recognition.",
  "You will make a positive impact on the world.",
  "You will find joy and contentment in your life.",
  "Your future is full of promise and potential.",
  "Your hard work and perseverance will pay off in the end.",
  "You will find love and companionship in the near future.",
  "Your creativity and imagination will lead to success and recognition.",
  "You will be blessed with good health and happiness.",
  "Your positive attitude and energy will attract success and happiness.",
  "You will find inner peace and contentment.",
  "Your dreams are within your reach if you believe in yourself.",
  "You will overcome any obstacle that comes your way.",
  "Your future is full of endless possibilities and opportunities.",
  "You will make a positive difference in the world.",
  "Your kindness and compassion will be rewarded.",
  "You will find joy and fulfillment in the little things in life.",
  "Your hard work and dedication will be recognized and appreciated.",
  "Your confidence and courage will lead to success and achievement.",
  "You will find meaning and purpose in your life.",
  "Your persistence and determination will pay off in the end.",
  "You will experience true happiness and fulfillment in your life.",
  "You will find love and companionship with someone special.",
  "Your unique talents and abilities will lead to success and recognition.",
  "You will be surrounded by positive energy and good vibes.",
  "Your future is full of promise and potential.",
  "Your hard work and dedication will pay off in the end.",
  "You will find success and fulfillment in your career.",
  "Your positive attitude and outlook on life will attract abundance and prosperity.",
  "You will make a positive impact on the lives of others.",
  "Your future is full of endless possibilities and opportunities.",
  "You will find happiness and contentment in your personal relationships.",
  "Your confidence and self-assurance will lead to success and achievement.",
  "You will achieve great things through hard work and dedication.",
  "Your creativity and imagination will lead to success and recognition.",
  "You will be surrounded by positivity and joy.",
  "You will find love and companionship with someone special.",
  "Your hard work and determination will pay off in the end.",
  "You will experience great success and prosperity in your life.",
  "Your future is full of promise and potential.",
  "You will overcome any obstacle that comes your way.",
  "You will find peace and tranquility in your life.",
  "You will make a positive difference in the world.",
  "Your positive attitude and energy will attract success and happiness.",
  "Your dreams are within your reach if you believe in yourself.",
  "You will achieve greatness through hard work and determination.",
  "Your creativity will lead to success and recognition.",
  "You will find inner peace and contentment.",
  "Your hard work will pay off in the end.",
  "You will find love and happiness.",
  "A new opportunity will come your way.",
  "You will be surrounded by positivity and joy.",
  "Your efforts will lead to success and prosperity.",
  "A new chapter in your life is about to begin.",
  "You will make a positive impact on the lives of those around you.",
  "Your future is full of possibilities and potential.",
  "You will find love and companionship with someone special.",
  "Your hard work and dedication will pay off in the end.",
  "You will achieve your goals and dreams through hard work and perseverance.",
  "Your unique talents and abilities will lead to success and recognition.",
  "You will make a positive difference in the world.",
  "Your future is full of promise and potential.",
  "You will find happiness and contentment in your life.",
  "Your positive attitude and energy will attract success and abundance.",
  "You will achieve greatness through hard work and dedication.",
  "Your creativity and imagination will lead to success and recognition.",
  "You will find inner peace and tranquility.",
  "Your hard work and determination will lead to success and prosperity.",
  "You will find love and companionship in the near future.",
  "Your confidence and self-assurance will lead to success and achievement.",
  "You will overcome any obstacles that come your way.",
  "Your future is full of endless possibilities and opportunities.",
  "You will make a difference in the world.",
  "Your kindness and compassion will be rewarded.",
  "Your dreams are within reach if you believe in yourself.",
  "You will find happiness and fulfillment in your personal relationships.",
  "Your positive outlook on life will attract abundance and prosperity.",
  "You will be surrounded by positivity and joy.",
  "You will achieve your goals through hard work and dedication.",
  "Your creativity will lead to success and recognition.",
  "You will find inner peace and contentment.",
  "Your hard work and perseverance will pay off in the end.",
  "You will find love and happiness with someone special.",
  "A new opportunity will come your way.",
  "Your future is full of possibilities and potential.",
  "You will be surrounded by positivity and good energy.",
  "Your efforts will lead to success and prosperity.",
  "A new chapter in your life is about to begin.",
  "You will make a positive impact on the lives of those around you.",
  "Your future is full of promise and potential.",
  "You will find love and companionship in the near future.",
  "Your hard work and dedication will pay off in the end.",
  "You will achieve your goals and dreams through hard work and perseverance.",
  "Your unique talents and abilities will lead to success and recognition.",
  "You will make a positive difference in the world.",
  "Your future is full of possibilities and opportunities.",
  "You will find happiness and contentment in your life.",
  "Your positive attitude and energy will attract success and abundance.",
  "You will achieve greatness through hard work and determination.",
  "Your creativity and imagination will lead to success and recognition.",
  "You will find inner peace and tranquility.",
  "Your hard work and determination will lead to success and prosperity.",
  "You will find love and companionship with someone special.",
  "Your confidence and self-assurance will lead to success and achievement.",
  "You will overcome any obstacles that come your way.",
  "Your future is full of endless possibilities and opportunities.",
  "You will make a difference in the world.",
  "Your kindness and compassion will be rewarded.",
  "Your dreams are within reach if you believe in yourself.",
  "You will find happiness and fulfillment in your personal relationships.",
  "Your positive outlook on life will attract abundance and prosperity.",
  "You will be surrounded by positivity and joy.",
  "You will achieve your goals through hard work and dedication.",
    "A beautiful, smart, and loving person will be coming into your life.",
    "A dubious friend may be an enemy in camouflage.",
    "A faithful friend is a strong defense.",
    "A fresh start will put you on your way.",
    "A friend asks only for your time not your money.",
    "A friend is a present you give yourself.",
    "A gambler not only will lose what he has, but also will lose what he doesn’t have.",
    "A golden egg of opportunity falls into your lap this month.",
    "A good time to finish up old tasks.",
    "A hunch is creativity trying to tell you something.",
    "A lifetime of happiness lies ahead of you.",
    "A light heart carries you through all the hard times.",
    "A new perspective will come with the new year. ",
    "A person is never too old to learn. ",
    "A person of words and not deeds is like a garden full of weeds. ",
    "A pleasant surprise is waiting for you.",
    "A smile is your personal welcome mat.",
    "A smooth long journey! Great expectations.",
    "A soft voice may be awfully persuasive.",
    "A truly rich life contains love and art in abundance.",
    "Accept something that you cannot change, and you will feel better.",
    "Adventure can be real happiness.",
    "Advice is like kissing. It costs nothing and is a pleasant thing to do. ",
    "Advice, when most needed, is least heeded.",
    "All things are difficult before they are easy.",
    "All will go well with your new project.",
    "All your hard work will soon pay off.",
    "Allow compassion to guide your decisions.",
    "An agreeable romance might begin to take on the appearance. ",
    "An important person will offer you support.",
    "An inch of time is an inch of gold.",
    "Be careful or you could fall for some tricks today.",
    "Be careful what you wish for. You might just get it.",
    "Be content with your lot; one cannot be first in everything.",
    "Be direct, usually one can accomplish more that way.",
    "Be kind to someone today.",
    "Beauty in its various forms appeals to you. ",
    "Because you demand more from yourself, others respect you deeply.",
    "Believe in yourself and others will too.",
    "Believe it can be done.",
    "Better ask twice than lose yourself once.",
    "Carve your name on your heart and not on marble.",
    "Change is happening in your life, so go with the flow!",
    "Competence like yours is underrated.",
    "Congratulations! You are on your way.",
    "Could I get some directions to your heart? ",
    "Courtesy is contagious.",
    "Curiosity kills boredom. Nothing can kill curiosity.",
    "Dedicate yourself with a calm mind to the task at hand.",
    "Depart not from the path which fate has you assigned.",
    "Determination is what you need now.",
    "Disbelief destroys the magic.",
    "Distance yourself from the vain.",
    "Do not be intimidated by the eloquence of others.",
    "Do not let ambitions overshadow small success.",
    "Do not make extra work for yourself.",
    "Do not underestimate yourself. Human beings have unlimited potentials.",
    "Don’t be discouraged, because every wrong attempt discarded is another step forward.",
    "Don’t confuse recklessness with confidence. ",
    "Don’t just think, act!",
    "Don’t let friends impose on you, work calmly and silently."
  ];

  const fortune = fortunes[Math.floor(Math.random() * fortunes.length)];
  document.getElementById("fortune-text").innerHTML = fortune;

  const crackingSound = document.getElementById("cracking-sound");
  crackingSound.currentTime = 0;
  crackingSound.play();
}

